1.	Как работает конструкция try catch finally?

В блоке try-catch, можно использовать блок finally, который выполнится в любом случае.

Например, если нам необходимо закрыть ресурс:
try {
     s = reader.readLine();
} catch (IOException e) {
     System.out.println(e.getMessage());
} finally {
     reader.close();
}

в finally можно получить ещё одно исключение, поэтому его также стоит обрабатывать дополнительным блоком try-catch, но это не совсем удобно, 
поскольку каждое новое исключение заглушает предыдущее.
